{% set major = "65" %}
{% set minor = "1" %}

package:
  name: icu
  version: {{ major }}.{{ minor }}

source:
  url: https://github.com/unicode-org/icu/releases/download/release-{{ major }}-{{ minor }}/icu4c-{{ major }}_{{ minor }}-src.tgz
  sha256: 53e37466b3d6d6d01ead029e3567d873a43a5d1c668ed2278e253b683136d948

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - make

  run:

about:
  home: http://site.icu-project.org/
  license: MIT
  license_file: LICENSE
