{% set version = "1.4.4" %}

package:
  name: zstd
  version: "{{ version }}"

source:
  url: https://github.com/facebook/zstd/releases/download/v{{ version }}/zstd-{{ version }}.tar.gz
  sha256: 59ef70ebb757ffe74a7b3fe9c305e2ba3350021a918d168a046c6300aeea9315

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make

  run:

about:
  home: https://github.com/facebook/zstd
  license: BSD
  summary: Zstandard - Fast real-time compression algorithm
