{% set version = "1.72.0" %}
{% set filename = "boost_%s.tar.bz2" % version.replace(".", "_") %}

package:
  name: boost
  version: "{{ version }}"

source:
  url: https://freefr.dl.sourceforge.net/project/boost/boost/{{ version }}/{{ filename }}
  sha256: 59c9b274bc451cf91a9ba1dd2c7fdcaf5d60b1b3aa83f2c9fa143417cc660722

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

  host:
    - python
    - zlib
    - bzip2
    - xz
    - zstd
    - icu

  run:
    - python
    - zlib
    - bzip2
    - xz
    - zstd
    - icu

about:
  home: https://github.com/boostorg/boost
  license: BSL-1.0
  Summary: Set of free portable C++ libraries
