{% set version = "1.73.0" %}
{% set filename = "boost_%s.tar.bz2" % version.replace(".", "_") %}

package:
  name: boost
  version: "{{ version }}"

source:
  url: https://freefr.dl.sourceforge.net/project/boost/boost/{{ version }}/{{ filename }}
  sha256: 4eb3b8d442b426dc35346235c8733b5ae35ba431690e38c6a8263dce9fcbb402

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

  host:
    - python =3.7
    - zlib
    - bzip2
    - xz
    - zstd
    - icu

  run:
    - python =3.7
    - zlib
    - bzip2
    - xz
    - zstd
    - icu

about:
  home: https://github.com/boostorg/boost
  license: BSL-1.0
  Summary: Set of free portable C++ libraries
