{% set version = "6.2.0" %}

package:
  name: gmp
  version: {{ version }}

source:
  url: https://gmplib.org/download/gmp/gmp-{{ version }}.tar.bz2
  sha256: f51c99cb114deb21a60075ffb494c1a210eb9d7cb729ed042ddb7de9534451ea

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - make

  run:

about:
  home: http://gmplib.org
  license: GPL 2 and LGPL 3
  Summary: The GNU Multiple Precision Arithmetic Library
