{% set version = "1.2.11" %}

package:
  name: zlib
  version: "{{ version }}"

source:
  url: http://zlib.net/zlib-{{ version }}.tar.gz
  sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make

  run:

about:
  home: http://zlib.net
  license: zlib
